server:
  port: ${KK_SERVER_PORT:58068}
  servlet:
    context-path: ${KK_CONTEXT_PATH:/}
    encoding:
      charset: utf-8
spring:
  servlet:
    #文件上传限制
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  ## FreeMarker 配置
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  ## redis连接，只有当cache.type = redis时才有用
  redisson:
    address: ${KK_SPRING_REDISSON_ADDRESS:127.0.0.1:6379}
    password: ${KK_SPRING_REDISSON_PASSWORD:}

logging:
#  config: classpath:logback-drm.xml
  level:
    root: info

## 缓存实现类型,可配置为redis(type = redis)实现（需要配置spring.redisson.address等参数）和 JDK 内置对象实现（type = jdk）,
## 不配默认为内嵌RocksDB(type = default)实现，
cache:
  type: ${KK_CACHE_TYPE:jdk}
  enabled: ${KK_CACHE_ENABLED:true}

## office转换服务的进程数，默认开启两个进程
office:
  plugin:
    server:
      ports: 2001,2002
    task:
      ## task 超时时间，默认五分钟
      timeout: 5m
  ## openoffice home路径 C:\\Program Files (x86)\\OpenOffice 4
  home: ${KK_OFFICE_HOME:default}
  #office类型文档(word ppt)样式，默认为图片(image)，可配置为pdf（预览时也有按钮切换）
  preview:
    #是否关闭office预览切换开关，默认为false，可配置为true关闭
    switch:
      disabled: ${KK_OFFICE_PREVIEW_SWITCH_DISABLED:false}
    ## office类型文档(word ppt)样式，默认为图片(image)，可配置为pdf（预览时也有按钮切换）
    type: ${KK_OFFICE_PREVIEW_TYPE:pdf}

#Tif类型图片浏览模式：tif（利用前端js插件浏览）；jpg（转换为jpg后前端显示）；pdf（转换为pdf后显示，便于打印）
tif:
  preview:
    type: ${KK_TIF_PREVIEW_TYPE:tif}

## 预览生成资源路径
file:
  dir: D:\\kkFileview\\
  upload:
    #是否禁用首页文件上传
    disable: ${KK_FILE_UPLOAD_ENABLED:false}
## 允许预览的本地文件夹 默认不允许任何本地文件被预览
local:
  preview:
    dir: ${KK_LOCAL_PREVIEW_DIR:default}
#信任站点，多个用','隔开，设置了之后，会限制只能预览来自信任站点列表的文件，默认不限制
trust:
  host: ${KK_TRUST_HOST:default}
#提供预览服务的地址，默认从请求url读，如果使用nginx等反向代理，需要手动设置
base:
  url: ${KK_BASE_URL:default}

#预览源为FTP时 FTP用户名，可在ftp url后面加参数ftp.username=ftpuser指定，不指定默认用配置的
ftp:
  username: ${KK_FTP_USERNAME:ftpuser}
  password: ${KK_FTP_PASSWORD:123456}
  control:
    #预览源为FTP时, FTP连接默认ControlEncoding(根据FTP服务器操作系统选择，Linux一般为UTF-8，Windows一般为GBK)，可在ftp url后面加参数ftp.control.encoding=UTF-8指定，不指定默认用配置的
    encoding: ${KK_FTP_CONTROL_ENCODING:UTF-8}

pdf:
  #是否禁止bookmark
  bookmark:
    disable: ${KK_PDF_BOOKMARK_DISABLE:true}
  #是否禁止下载转换生成的pdf文件
  download:
    disable: ${KK_PDF_DOWNLOAD_DISABLE:true}
  #是否禁止打开文件
  openFile:
    disable: ${KK_PDF_OPEN_FILE_DISABLE:true}
  #是否禁止演示模式
  presentationMode:
    disable: ${KK_PDF_PRESENTATION_MODE_DISABLE:true}
  #是否禁止打印转换生成的pdf文件
  print:
    disable: ${KK_PDF_PRINT_DISABLE:true}

#支持转换的视频类型
convertMedias: ${KK_CONVERTMEDIAS:avi,mov,wmv,mkv,3gp,rm}
#文本类型，默认如下，可自定义添加
simText: ${KK_SIMTEXT:txt,html,htm,asp,jsp,xml,json,properties,md,gitignore,log,java,py,c,cpp,sql,sh,bat,m,bas,prg,cmd}
#多媒体类型，默认如下，可自定义添加
media: ${KK_MEDIA:mp3,wav,mp4,flv}


#水印内容
#如需取消水印，内容设置为空即可，例：watermark.txt = ${WATERMARK_TXT:}
watermark:
  txt: ${WATERMARK_TXT:}
  #水印透明度，要求设置在大于等于0.005，小于1
  alpha: ${WATERMARK_ALPHA:0.2}
  #水印倾斜度数，要求设置在大于等于0，小于90
  angle: ${WATERMARK_ANGLE:10}
  #水印字体颜色
  color: ${WATERMARK_COLOR:black}
  #水印字体
  font: ${WATERMARK_FONT:微软雅黑}
  #水印字体大小
  fontsize: ${WATERMARK_FONTSIZE:18px}
  #水印高度
  height: ${WATERMARK_HEIGHT:80}
  #水印宽度
  width: ${WATERMARK_WIDTH:180}
  #水印x轴间隔
  x:
    space: ${WATERMARK_X_SPACE:10}
  #水印y轴间隔
  y:
    space: ${WATERMARK_Y_SPACE:10}

